name: secur-sn
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas>=2.2
  - numpy>=1.26
  - matplotlib>=3.8
  - seaborn>=0.13
  - scikit-learn>=1.4
  - pyspark=3.5.1
  - pandera>=0.20
  - pillow>=10.0
  - duckdb>=1.0
  - pytest>=8.0
  - pip
  - pip:
      - kafka-python>=2.0.2
      - happybase>=1.2.0
      - thrift>=0.20.0
